name: Backup server continuous integration
run-name: backend_ci

on: [push]
jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and start docker containers
      run: docker-compose up -d --build
    - name: Run the lint check
      run: docker exec -it backend make lint
    - name: Run the unit test (alongside the coverage generation)
      run: docker exec -it backend make coverage_gen
    - name: Displays the result in the shell
      run: docker exec -it backend make coverage_shell
    - name: Stop the containers
      run: docker compose down --volumes
    - name: End of continuous integration
      run: echo "Job done with status ${{job.status}}!"