services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - PUBLIC_URL=127.0.0.1
      - JEST_CONFIG=./config/jest.config.js react-scripts test
    volumes:
      - static:/static
    command: sh -c "cp -r /home/build/static/* /static ; nginx -g 'daemon off;'"

  embeddings:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    mem_limit: 2g

  channels:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  db:
    image: ankane/pgvector
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: backend
    command: sh -c "make migrate ; make run"
    volumes:
      - static:/backend/static/
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env

volumes:
  postgres_data:
  static: