services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PUBLIC_URL=127.0.0.1
      - JEST_CONFIG=./config/jest.config.js react-scripts test
    volumes:
      - static:/static
    command: sh -c "cp -r /home/build/static/* /static ; nginx -g 'daemon off;'"

  embeddings:
    image: opensearchproject/opensearch:latest
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    mem_limit: 2g

  channels:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"

  backend:
    build: backend
    command: sh -c "make migrate ; make run"
    volumes:
      - static:/backend/static/
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      embeddings:
        condition: service_healthy
      db:
        condition: service_healthy
      channels:
        condition: service_healthy
    environment:
      - DB_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  postgres_data:
  static: