# Generated by Django 5.1.1 on 2025-04-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('BOT', 'CHATBOT_AGENT'), ('HUMAN', 'USER')], verbose_name='Text author')),
                ('text', models.CharField(verbose_name='Input')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot.conversation', verbose_name='Related conversation')),
            ],
        ),
    ]
