# Generated by Django 5.1.1 on 2025-04-16 15:08

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
