# Generated by Django 5.1.1 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceEntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(verbose_name='Data type')),
                ('value', models.CharField(verbose_name='Value')),
            ],
        ),
        migrations.RenameModel(
            old_name='ChatbotInput',
            new_name='ChatbotSentence',
        ),
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ConversationModel',
        ),
    ]
