# Generated by Django 5.1.1 on 2025-04-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_sentenceentitymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('understood_data', models.CharField(verbose_name='Understood data')),
                ('found_data', models.CharField(verbose_name='Found device data primary keys')),
                ('text_answer', models.CharField(verbose_name='Answer (generated by the bot)')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbot.botanswer', verbose_name='Previous bot answer')),
            ],
        ),
    ]
