# Generated by Django 5.1.1 on 2025-04-17 12:44

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_enablepgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(verbose_name='Tags')),
                ('sentence', models.CharField(verbose_name='Sentence')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Embedding of the sentence', null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ChatbotInput',
            new_name='ChatbotSentence',
        ),
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ConversationModel',
        ),
        migrations.CreateModel(
            name='SentenceEntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(verbose_name='Data type')),
                ('input', models.CharField(verbose_name='Value')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot.sentence', verbose_name='Sentence including the input')),
            ],
        ),
    ]
