# Generated by Django 5.1.1 on 2025-04-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_botanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botanswer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='botanswer',
            name='text_answer',
        ),
        migrations.AddField(
            model_name='botanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotsentence', verbose_name='Answer (generated by the bot)'),
        ),
        migrations.AlterField(
            model_name='chatbotsentence',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbot.conversationmodel', verbose_name='Related conversation'),
        ),
    ]
