# Generated by Django 5.1.1 on 2025-04-29 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_botanswer_parent_remove_botanswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 6, 44, 10, 751245)),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='BotAnswer',
        ),
    ]
