# Generated by Django 5.1.1 on 2025-05-07 13:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_conversationmodel_created_at_conversationmodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 0, 0, 0), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Summary'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('BOT', 'CHATBOT_AGENT'), ('HUMAN', 'USER')], verbose_name='Text author')),
                ('text', models.CharField(verbose_name='Input')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 5, 7, 13, 53, 59, 868389), verbose_name='Timestamp')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbot.conversationmodel', verbose_name='Related conversation')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotSentence',
        ),
    ]
